"""create personas, persona_states, episodic_events

Revision ID: 08c4a85336ec
Revises: 
Create Date: 2026-08-17 21:32:06.597772

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08c4a85336ec'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=False),
    sa.Column('avatar_initials', sa.String(length=4), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('character', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('boundaries', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('emotion_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('relationship_stages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('baseline_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('research_scope', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_states',
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('persona_id', sa.String(length=64), nullable=False),
    sa.Column('emotion', sa.String(length=50), nullable=False),
    sa.Column('emotion_intensity', sa.Double(), nullable=False),
    sa.Column('emotion_cause', sa.Text(), nullable=True),
    sa.Column('relationship_stage', sa.String(length=50), nullable=False),
    sa.Column('rapport_score', sa.Double(), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=False),
    sa.Column('known_facts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_persona_states_persona_id'), 'persona_states', ['persona_id'], unique=False)
    op.create_table('episodic_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('emotion_impact', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['persona_states.conversation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodic_events_conversation_id'), 'episodic_events', ['conversation_id'], unique=False)
    op.create_index('ix_episodic_events_conversation_turn', 'episodic_events', ['conversation_id', 'turn_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_episodic_events_conversation_turn', table_name='episodic_events')
    op.drop_index(op.f('ix_episodic_events_conversation_id'), table_name='episodic_events')
    op.drop_table('episodic_events')
    op.drop_index(op.f('ix_persona_states_persona_id'), table_name='persona_states')
    op.drop_table('persona_states')
    op.drop_table('personas')
    # ### end Alembic commands ###
